# services:
#   n8n-imob:
#     image: n8nio/n8n
#     ports:
#       - "5678:5678"
#     volumes:
#       - ./src:/home/node/.n8n
#     environment:
#       GENERIC_TIMEZONE: America/Sao_Paulo
#     restart: unless-stopped
#     networks:
#       - n8n-network-imob
 
# networks:
#   n8n-network-imob:
#     driver: bridge

services:
  n8n-imob:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
     # - N8N_PROTOCOL=https
      - N8N_SECURE_COOKIE = false 
      - NODE_ENV=production
      - WEBHOOK_URL=http://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    ports:
      - "5678:5678"
    volumes:
      - n8n-imob:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n-imob: