services:
  #INICIA O CONTAINER DO N8N
  n8n-imob:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-imob
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
     # - N8N_PROTOCOL=https
      - N8N_SECURE_COOKIE=false 
      - NODE_ENV=production
      - WEBHOOK_URL=http://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
  
  #INICIA O SERVIÇO DO POCKETBASE
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile-pocketbase
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/app/pb_data
    restart: unless-stopped

volumes:
  n8n_data:
  pocketbase_data:


  
